### ISSUE TITLE
Adicionar uma tela de carregamento ( Estética )

### ISSUE THREAD

**Issue by RuisuGit** [DarkMod3/NightBox#1]
Uma breve alternativa é trocar o código da linha 9, que contem:
<code>@echo off && mode 15,1 && color 07</code> por <code>@echo off && color 07</code>

logo, na linha seguinte, adicionar uma tela de carregamento ( pode ser estática )

Porque dá uma leve impressão de que o arquivo .bat crashou, mas está baixando alguns arquivos ( como o aria2c que presenciei no código )

**Comment by DarkMod3** [comment]
Ok acabei de adicionar uma que fala que os plugins estão sendo baixados mas ela ainda é estatica, daqui algumas atualizções eu pretendo fazer uma tela de carregamento funcional

Obrigado pelo aviso @RuisuGit
